# Generated by Django 4.2.6 on 2023-10-27 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sand',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 18, 0)),
        ),
    ]
